version: '3.8'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails -v && bundle exec rails s -b 0.0.0.0 -e production"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      DATABASE_URL: <%= ENV["RDS_HOST"] %>
      SECRET_KEY_BASE: <%= ENV["RAILS_SECRET"] %>
      # AWS_ACCESS_KEY_ID: <%= optional if using S3 >
      # AWS_SECRET_ACCESS_KEY: <%= optional if using S3 >
    volumes:
      - .:/app
    restart: always
