version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: <%= ENV["RDS_USERNAME"] %>
      POSTGRES_PASSWORD: <%= ENV["RDS_PASSWORD"] %>
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: <%= ENV["RDS_HOST"] %>
    depends_on:
      - db

volumes:
  pgdata:
