services:
  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./:/app:ro
      - nginx_runtime:/etc/nginx/runtime
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/runtime/cloudfront-realip.conf:/etc/nginx/runtime/cloudfront-realip.conf:ro
      - /var/log/bootcore/nginx:/var/log/nginx
    restart: unless-stopped
  web:
    build: .
    command: bash -lc "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    expose:
      - "3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"   # <-- maps to the EC2 host from inside container
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      RAILS_LOG_LEVEL: ${RAILS_LOG_LEVEL:-info}
      PORT: "3000"
      RDS_HOST: host.docker.internal
    volumes:
      - /var/log/bootcore/rails:/app/log

volumes:
  nginx_runtime:
