require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cover_letters", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CoverLetter. As you add validations to CoverLetter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CoverLetter.create! valid_attributes
      get cover_letters_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cover_letter = CoverLetter.create! valid_attributes
      get cover_letter_url(cover_letter)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cover_letter_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cover_letter = CoverLetter.create! valid_attributes
      get edit_cover_letter_url(cover_letter)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CoverLetter" do
        expect {
          post cover_letters_url, params: { cover_letter: valid_attributes }
        }.to change(CoverLetter, :count).by(1)
      end

      it "redirects to the created cover_letter" do
        post cover_letters_url, params: { cover_letter: valid_attributes }
        expect(response).to redirect_to(cover_letter_url(CoverLetter.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CoverLetter" do
        expect {
          post cover_letters_url, params: { cover_letter: invalid_attributes }
        }.to change(CoverLetter, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post cover_letters_url, params: { cover_letter: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cover_letter" do
        cover_letter = CoverLetter.create! valid_attributes
        patch cover_letter_url(cover_letter), params: { cover_letter: new_attributes }
        cover_letter.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cover_letter" do
        cover_letter = CoverLetter.create! valid_attributes
        patch cover_letter_url(cover_letter), params: { cover_letter: new_attributes }
        cover_letter.reload
        expect(response).to redirect_to(cover_letter_url(cover_letter))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        cover_letter = CoverLetter.create! valid_attributes
        patch cover_letter_url(cover_letter), params: { cover_letter: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cover_letter" do
      cover_letter = CoverLetter.create! valid_attributes
      expect {
        delete cover_letter_url(cover_letter)
      }.to change(CoverLetter, :count).by(-1)
    end

    it "redirects to the cover_letters list" do
      cover_letter = CoverLetter.create! valid_attributes
      delete cover_letter_url(cover_letter)
      expect(response).to redirect_to(cover_letters_url)
    end
  end
end
