
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bootcore_development

test:
  <<: *default
  database: bootcore_test

production:
  database: bootcore_prod
  username: <%= ENV["RDS_USERNAME"] %>
  password: <%= ENV["RDS_PASSWORD"] %>
  host: <%= ENV["RDS_HOST"] %>
  port: 5432
