# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d571466d6abc1f94642db8a48ae100b4a3d1400a7c018cfaeb47029c2190661fd45e8751b4d28c9ed25909c8b1e32ff81b59c70d49588dd21d40ef512289c222
  sendgrid_username: app27600473@heroku.com
  sendgrid_password: o6tiqfxu
test:
  secret_key_base: ad3249d0b1446ef4cd78ec421b46658d38d6e661aa6c25d08c691d98134aa99daa43a54c31bcaac9ebc67130239a6f820378778eb03d210dd0784de1ef34a89a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sendgrid_username: app27600473@heroku.com
  sendgrid_password: o6tiqfxu
